# Generated by Django 5.1.4 on 2025-02-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_profilesetup_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='profilesetup',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_setup/'),
        ),
    ]
