# Generated by Django 5.1.4 on 2025-03-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follow_status',
            field=models.BooleanField(default=False),
        ),
    ]
